### ISSUE TITLE
Update stable version in repo from 2.1.0 to 2.1.7

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.vis-justgage#100]
# Think about update stable version to 2.1.7
**Version**: stable=**2.1.0** (103 days old) => latest=**2.1.7** (15 days old)
**Installs**: stable=**5714** (61.61%), latest=**662** (7.14%), total=**9274**

Click to use [developer portal](https://www.iobroker.dev/adapter/vis-justgage/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L2861)

Note: This is an automatically generated message and not personally authored by bluefox!
      Do not close this issue manually as a new issue will be created if condition for update still exists
      @mcm1957 for evidence

**Comment by mcm1957** [comment]
Is there any reason to delay updating stable any longer?
Please drop a commit if you know any reason to refrain from updating.

If there is no response until 9.4.2024 we could decide to update anyway.

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 2.1.7 but the current stable version is already 2.1.7.

So this issue should be closed.

@mcm1957 for evidence
