### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [iobroker-community-adapters/ioBroker.vis-justgage#19]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/Pmant/ioBroker.vis-justgage

- [ ] [E104] No common.titleLang found in io-package.json
- [ ] [E150] No common.connectionType found in io-package.json
- [ ] [E152] No common.dataSource found in io-package.json
- [ ] [E300] Not found on travis. Please setup travis
- [ ] [E801] No repository about text found. Please go to "https://github.com/Pmant/ioBroker.vis-justgage", press the settings button beside the about title and add the description.
- [ ] [E802] No topics found in the repository. Please go to "https://github.com/Pmant/ioBroker.vis-justgage", press the settings button beside the about title and add some topics.

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?

**Comment by mcm1957** [comment]
obsolete
