### ISSUE TITLE
no graphic with vis 2

### ISSUE THREAD

**Issue by DerTom1978** [iobroker-community-adapters/ioBroker.vis-justgage#40]
I have set up a new system to test vis 2.
With vis 1, everything is visible and working as usual.
under vis 2 I can select the widget and make all the settings, but no graphic appears.
I tried the complete installation (incl. new iobroker) again - same result.

BR
Tom

**Comment by DerTom1978** [comment]
forgotten:
VIS: 2.3.4
justgage: 2.0

npm: 9.8.1
node: 18.18.2

**Comment by DerTom1978** [comment]
Hello,

update to VIS 2.4 - same problem

BR
Tom

**Comment by DerTom1978** [comment]
workaround
either revert to V1.0.1 after installing justgage: 2.0 with the expert mode or install version 1.0.1 straight away with "iobroker add vis-justgage@1.0.1 auto --host YOURHOSTNAME --debug".

The graphics will then be visible again.

After that, however, another problem has arisen (only now visible):
The display in the widget is frozen after a page change or restart of VIS. Although the values in the objects change, nothing is visible. The widget remains at value 0.
Only a setting change (colour or something else) in the editor activates the widget again.

Another problem: RGB values (rgba(135,135,241,1) are ignored.
If a hex value is entered (#8989F1) it works.

Another problem: End of Sector 1 or 2 - colour values are ignored

Best regards
The Tom

**Comment by mcm1957** [comment]
Please retest with 2.0.1 (available at LATEST repo 25.11.2023)

Problem ist likely NOT caused by vis2 but 2.0.0 was generally broken as it was missing some files.
Sorry.

If Widget is working in general again please open a new issue describing the remaining problems adn icnlude the used versions (adapter, vis(vis-2, js-controller)

**Comment by mcm1957** [comment]
Please retest with 2.0.2. 

As stated here https://github.com/iobroker-community-adapters/ioBroker.vis-justgage/issues/54#issuecomment-1826436324 try to DEINSTALL vis-justgage and install 2.0.2 afterwards.

If the widget is still not visible, please reopen the issue.

For other problems, please open new seperate issue. I suggest to discuss problems like not updating or problems specifying colours at forum first. You might get a faster response there.

vis-justgage is not actively developed currently. If someone has interrest to do it, please let us know,
