### ISSUE TITLE
Widget wird nicht angezeigt in VIS-2

### ISSUE THREAD

**Issue by zaphod2** [iobroker-community-adapters/ioBroker.vis-justgage#78]
In VIS-2 gibt es Ladeprobleme mit dem Widget.
Beim Laden der Seite werden die Werte im Widget nicht angezeigt.
Es wird z.B. ein Seitenwechsel benötigt, dann wird auch das Widget korrekt angezeigt.
Die Funktion ist gegeben, es betrifft lediglich die Anzeige.
vis-justgage v2.1.0
Vis-2 v2.9.8

**Comment by jens-maus** [comment]
Auch ich kann bestätigen das dieses widget leider wohl noch nicht ganz vis-2 kompatibel ist. Wäre schön wenn es entsprechend kompatibel gemacht werden könnte.

**Comment by GermanBluefox** [comment]
Fixed in 2.1.4
